import {test,expect} from '@playwright/test';
import {randomUUID} from 'node:crypto';

test('long previews build ordered listening parts without paid conversions',async({page,request})=>{
 test.setTimeout(180000);
 const imported=await request.post('/api/import',{data:{text:'[script: Long preview test]\n[cast: Reader | Long preview actor]\n[scene: One long scene]\n'+Array.from({length:125},(_,i)=>`[Reader]\nLine ${i+1}.`).join('\n'),request_id:randomUUID().replaceAll('-','')}});
 expect(imported.ok(),await imported.text()).toBeTruthy();
 const project=await imported.json();
 await page.goto('/');await page.getByLabel('Current project').selectOption(project.id);
 await page.getByRole('button',{name:'Generate scene preview',exact:true}).click();
 const preview=page.getByLabel('Whole scene preview');
 await expect(preview.getByRole('heading',{name:'Part 4 of 4 · Lines 121–125'})).toBeVisible({timeout:150000});
 await expect(preview.locator('audio')).toHaveCount(4);
 await expect(preview.getByRole('heading',{name:'Part 1 of 4 · Lines 1–40'})).toBeVisible();
 const player=page.getByLabel('Play scene part 4');
 await player.evaluate((el:HTMLAudioElement)=>el.play());
 await expect.poll(()=>player.evaluate((el:HTMLAudioElement)=>el.currentTime)).toBeGreaterThan(0);
 await player.evaluate((el:HTMLAudioElement)=>el.pause());
 const workspace=await (await request.get('/api/workspace')).json();
 const scene=workspace.scenes.find((s:{project_id:string})=>s.project_id===project.id);
 const endpoint=`/api/actor/scenes/${scene.id}/preview`;
 expect((await request.post(endpoint,{data:{part:4}})).status()).toBe(400);
 expect((await request.post(endpoint,{data:{part:1,snapshot:'outdated'}})).status()).toBe(409);
 const status=await (await request.get(`/api/actor/scenes/${scene.id}/voicing`)).json();
 expect(status.run).toBeNull();
 // One recorded line can convert even in a >120-line unfinished scene.
 const line=workspace.events.find((e:{scene_id:string})=>e.scene_id===scene.id);
 const actor=workspace.actors.find((a:{name:string})=>a.name==='Long preview actor');
 const wav=Buffer.alloc(32044);wav.write('RIFF',0);wav.writeUInt32LE(32036,4);wav.write('WAVEfmt ',8);wav.writeUInt32LE(16,16);wav.writeUInt16LE(1,20);wav.writeUInt16LE(1,22);wav.writeUInt32LE(16000,24);wav.writeUInt32LE(32000,28);wav.writeUInt16LE(2,32);wav.writeUInt16LE(16,34);wav.write('data',36);wav.writeUInt32LE(32000,40);
 const upload=()=>request.post(`/api/actor/events/${line.id}/takes?revision=1&as_actor=${actor.id}`,{headers:{'Content-Type':'audio/wav','X-Upload-ID':randomUUID().replaceAll('-','')},data:wav});
 expect((await upload()).ok()).toBeTruthy();
 expect((await request.put(`/api/characters/${line.character_id}/target-voice`,{data:{voice_id:'voice-wolf'}})).ok()).toBeTruthy();
 await page.reload();await page.getByLabel('Current project').selectOption(project.id);
 await page.getByText('Converted lines',{exact:true}).click();
 await expect(page.getByRole('button',{name:'Voice scene',exact:true})).toBeDisabled();
 const before=(await (await request.get('http://127.0.0.1:18089/test/state')).json()).calls;
 page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'Convert line 1',exact:true}).click();
 await expect(page.getByLabel('ElevenLabs scene')).toContainText('Line conversion complete',{timeout:60000});
 expect((await (await request.get('http://127.0.0.1:18089/test/state')).json()).calls).toBe(before+1);
 const converted=await (await request.post(endpoint,{data:{part:0}})).json();expect(converted.converted_lines).toBe(1);
 expect((await (await request.get(`/api/actor/scenes/${scene.id}/voicing`)).json()).finished).toBeNull();
 await request.put(`/api/characters/${line.character_id}/target-voice`,{data:{voice_id:'voice-owl'}});
 const changed=await (await request.post(endpoint,{data:{part:0}})).json();expect(changed.converted_lines).toBe(0);expect(changed.url).not.toBe(converted.url);
 await request.put(`/api/characters/${line.character_id}/target-voice`,{data:{voice_id:'voice-wolf'}});
 expect((await (await request.post(endpoint,{data:{part:0}})).json()).url).toBe(converted.url);
 expect((await upload()).ok()).toBeTruthy();
 expect((await (await request.post(endpoint,{data:{part:0}})).json()).converted_lines).toBe(0);
 expect((await (await request.get('http://127.0.0.1:18089/test/state')).json()).calls).toBe(before+1);
});
