import {test,expect} from '@playwright/test';

test('an actor records, previews, saves multiple takes and replays history',async({browser,request})=>{
 test.setTimeout(90000);
 const post=async(path:string,body:unknown)=>{const response=await request.post(path,{data:body});expect(response.ok()).toBeTruthy();return response.json();};
 const project=await post('/api/projects',{name:'Recording browser story'});
 const actor=await post('/api/actors',{name:'Hazel recording test'});
 const character=await post('/api/characters',{name:'Little wolf',project_id:project.id});
 const scene=await post('/api/scenes',{name:'The brave little wolf',project_id:project.id,position:1});
 await request.put(`/api/actors/${actor.id}/login`,{data:{email:'browser-actor@example.test'}});
 await request.put(`/api/assignments/${character.id}`,{data:{actor_id:actor.id}});
 for(let i=1;i<=2;i++)await post('/api/events',{project_id:project.id,scene_id:scene.id,character_id:character.id,text:i===1?'I can be brave, even when the forest feels big.':'Will you come with me?',direction:i===1?'Start quietly, then sound a little braver.':'Hopefully',position:i,start_ms:0});
 const context=await browser.newContext({baseURL:'http://127.0.0.1:18088',extraHTTPHeaders:{Authorization:`Bearer ${process.env.STORYFORGE_DEV_AUTH_TOKEN}`,'X-StoryForge-Dev-Email':'browser-actor@example.test'},permissions:['microphone']});
 const page=await context.newPage();const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/');
 await expect(page.getByRole('heading',{level:1})).toContainText('Hazel recording test');
 await expect(page.getByRole('button',{name:'Manage scripts',exact:true})).toHaveCount(0);
 await page.getByRole('button',{name:/The brave little wolf/}).click();
 await expect(page.locator('.performance-text')).toHaveText('I can be brave, even when the forest feels big.');
 await expect(page.locator('.performance-direction')).toContainText('Start quietly');
 await page.getByRole('button',{name:'● Record',exact:true}).click();
 await expect(page.getByRole('status')).toContainText('Recording');
 await expect(page.getByRole('status')).toContainText('0:01');
 await page.getByRole('button',{name:'■ Stop recording'}).click();
 await expect(page.getByRole('button',{name:'Save take',exact:true})).toBeVisible();
 expect(await (await context.request.get('/api/actor/takes')).json()).toHaveLength(0);
 const preview=page.getByLabel('Listen to your new take');
 await preview.evaluate((el:HTMLAudioElement)=>el.play());
 await expect.poll(()=>preview.evaluate((el:HTMLAudioElement)=>el.currentTime)).toBeGreaterThan(0);
 await preview.evaluate((el:HTMLAudioElement)=>el.pause());
 page.once('dialog',d=>d.dismiss());await page.getByRole('button',{name:'Next line →'}).click();
 await expect(page.locator('.performance-text')).toContainText('I can be brave');
 // A failed upload retains the blob and retry ID. The retry saves only one take.
 await page.route('**/api/actor/events/*/takes?*',route=>route.fulfill({status:503,contentType:'application/json',body:'{"error":"Temporary upload failure"}'}),{times:1});
 await page.getByRole('button',{name:'Save take',exact:true}).click();
 await expect(page.getByRole('alert')).toContainText('Temporary upload failure');
 await expect(preview).toBeVisible();
 await page.getByRole('button',{name:'Save take',exact:true}).click();
 await expect(page.locator('.take-card')).toHaveCount(1);
 await page.getByRole('button',{name:'● Record another take'}).click();
 await expect(page.getByRole('status')).toContainText('0:01');
 await page.getByRole('button',{name:'■ Stop recording'}).click();
 await page.getByRole('button',{name:'Save take',exact:true}).click();
 await expect(page.locator('.take-card')).toHaveCount(2);
 await page.locator('.take-card').first().getByRole('button',{name:'☆ Make preferred'}).click();
 await expect(page.locator('.take-card').first().getByRole('button',{name:'★ Preferred take'})).toBeVisible();
 await page.setViewportSize({width:1365,height:1000});
 await page.screenshot({path:'test-results/actor-studio-desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
 await page.screenshot({path:'test-results/actor-studio-mobile.png',fullPage:true});
 await page.reload();
 await page.getByRole('button',{name:/My saved takes/}).click();
 await expect(page.locator('.take-card')).toHaveCount(2);
 const saved=page.getByLabel('Play take 1');await saved.evaluate((el:HTMLAudioElement)=>el.play());
 await expect.poll(()=>saved.evaluate((el:HTMLAudioElement)=>el.currentTime)).toBeGreaterThan(0);
 expect(errors).toEqual([]);await context.close();
});
